name: Update All Docker Tags in README

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs monthly on the 1st at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get latest tags and update README
        run: |
          declare -a images=(
            "paicbusinessdev/smsc-routing-module"
            "paicbusinessdev/orchestrator-module"
            "paicbusinessdev/retries-module"
            "paicbusinessdev/db-insert-data"
            "paicbusinessdev/smpp-server-module"
            "paicbusinessdev/smpp-client-module"
            "paicbusinessdev/http-server-module"
            "paicbusinessdev/http-client-module"
            "paicbusinessdev/ss7-module"
            "paicbusinessdev/smsc-management-be"
            "paicbusinessdev/smsc-management-fe"
          )

          for image in "${images[@]}"; do
            TAG=$(curl -s "https://hub.docker.com/v2/repositories/${image}/tags?page_size=1&ordering=last_updated" | jq -r '.results[0].name')
            echo "Found latest tag for $image: $TAG"
            escaped_image=$(echo $image | sed 's/\//\\\//g')
            sed -i -E "s|(${escaped_image}:)latest|\1$TAG|g" README.md
          done

      - name: Create Pull Request if changes exist
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update Docker image tags in README"
          title: "chore: update Docker image tags in README"
          body: |
            This PR updates all `:latest` Docker image references in the README with the most recent stable tags from Docker Hub.

            - Triggered automatically via GitHub Actions
            - Based on tags: latest updated version per image
          branch: auto/update-docker-tags
          delete-branch: true
